// すべての定数をエクスポート
const { SUCCESS_MESSAGES, ERROR_TYPES, VALIDATION_MESSAGES, ERROR_MESSAGES, LOG_MESSAGES } = require('./messages');
const { BOOK_STATUS, VALID_STATUSES, DEFAULT_STATUS } = require('./status');

module.exports = {
  SUCCESS_MESSAGES,
  ERROR_TYPES,
  VALIDATION_MESSAGES,
  ERROR_MESSAGES,
  LOG_MESSAGES,
  BOOK_STATUS,
  VALID_STATUSES,
  DEFAULT_STATUS
};
